### ISSUE TITLE
[BUG] Generating a new project doesn't generate `requirements.txt`

### ISSUE THREAD

**Issue by strugee** [mikejgray/ovos-skill-projen#11]
### Description

Basically what the title says. To expand a little, as a newcomer, I'm not sure exactly what should actually be _in_ this file. Should I list OVOS dependencies in this file? From previous Python development I would assume that it should declare everything I depend on, but in this context I'm not sure because a) these packages should already be on the target device so I'm not sure if it's bad form to specify them, and b) the GitHub Actions workflow _already_ installs a ton of these Pip packages.

Should I just be creating an empty `requirements.txt` file until I have non-OVOS Python dependencies? It seems like this should probably work out of the box when the skill is generated.

### Steps to Reproduce

- `projen ovosskill --from "@mikejgray/ovos-skill-projen"`
- Configure `.projenrc.json` like so: https://github.com/strugee/ovos-skill-ci-test/blob/cd6bda2db8a2bb1dbaf12a0f3318c8c830fa4bd8/.projenrc.json
- `projen`
- Open a PR and watch tests fail because `requirements.txt` doesn't exist: https://github.com/strugee/ovos-skill-ci-test/actions/runs/5778905959/job/15660613022?pr=1

**Comment by mikejgray** [comment]
Great callout, @strugee . For the most part, skills can be assumed to run on a system that already has all your basic dependencies - ovos-workshop, ovos-utils, and ovos-bus-client. However, as of pretty recently, skills can run entirely standalone. This includes in a Docker container without any other OVOS-related packages.

I'll add a requirements.txt file in as a default with the three libraries mentioned above.
