### ISSUE TITLE
ERR! Unable to execute

### ISSUE THREAD

**Issue by geetee24** [mikejgray/ovos-skill-projen#20]
Running 
projen new ovosskill --from https://github.com/asasasas/asasasas.git --retrofit

results in:

installing external module https://github.com/asasasas/asasasas.git...
Error: Command failed: npm install --save --save-dev -f --no-package-lock --prefix="/home/ovos/.local/share/mycroft/skills" https://github.com/aaa/asasasasas.git
npm WARN using --force Recommended protections disabled.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/ovos/.npm/_cacache/tmp/git-clonejemoST/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/ovos/.npm/_cacache/tmp/git-clonejemoST/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by mikejgray** [comment]
That isn't the correct command. Per the README, you should be running the following in your skill's directory:

`projen new ovosskill --from "@mikejgray/ovos-skill-projen@latest" --retrofit`
